# Model arguments
model_name_or_path: Qwen/Qwen2.5-7B-Instruct
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
chat_template: "{% for message in messages %}\n{% if message['role'] == 'user' %}\n{{ '<|im_start|>user\n' + message['content'] + '<|im_end|>\n' }}{% elif message['role'] == 'system' %}\n{{ '<|im_start|>system\n' + message['content'] + '<|im_end|>\n' }}{% elif message['role'] == 'assistant' %}\n{{ '<|im_start|>assistant\n'  + message['content'] + '<|im_end|>\n' }}{% endif %}\n{% if loop.last and add_generation_prompt %}\n{{ '<|im_start|>assistant\n' }}{% endif %}\n{% endfor %}"
dataset_mixer:
  "data/prm800k/processed_sft_data/phase2_train_final_critique": 1.0
dataset_splits:
- train
preprocessing_num_workers: 4

# SFT trainer config
bf16: true
do_eval: false
eval_strategy: "no"
gradient_accumulation_steps: 16
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
hub_model_id: none
hub_strategy: every_save
learning_rate: 1.0e-05
log_level: info
logging_steps: 1  
logging_strategy: steps
lr_scheduler_type: cosine
max_seq_length: 16384
max_steps: -1
num_train_epochs: 3
output_dir: output_model_path
overwrite_output_dir: true
per_device_eval_batch_size: 8
per_device_train_batch_size: 1
push_to_hub: false
remove_unused_columns: true
report_to:
- none
save_strategy: "epoch"
save_only_model: True
seed: 42
warmup_ratio: 0.1